package tn.musego.app;


import com.codename1.io.Log;
import com.codename1.ui.Dialog;
import com.codename1.ui.Form;
import com.codename1.ui.Toolbar;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import tn.musego.app.gui.SplashScreen;

import static com.codename1.ui.CN.*;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose
 * of building native mobile applications using Java.
 */
public class MyApplication {

    public static Resources theme;
    private Form current;

    public void init(Object context) {
        // use two network threads instead of one
        updateNetworkThreadCount(2);

        theme = UIManager.initFirstTheme("/theme_1");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature
        Log.bindCrashProtection(true);

        addNetworkErrorListener(err -> {
            // prevent the event from propagating
            err.consume();
            if (err.getError() != null) {
                Log.e(err.getError());
                Dialog.show("Connection Error", "There was a networking error in the connection to the server", "OK", null);
            }
        });
    }

    public void start() {
        if (current != null) {
            current.show();
            return;
        }

        runApp();
    }

    /**
     * This method is invoked by start to show the first form of the application
     */
    public void runApp() {
        new SplashScreen().show();
    }


    /**
     * Callback when the app is suspended
     */
    public void stop() {
        current = getCurrentForm();
        if (current instanceof Dialog) {
            ((Dialog) current).dispose();
            current = getCurrentForm();
        }
    }

    /**
     * Callback when the app is destroyed
     */
    public void destroy() {
    }

}
